language: node_js
node_js:
  - 16

branches:
  only:
    - main
    - dep-inclusions

cache:
  directories:
    - node_modules

before_script:
  - sudo chown -R $USER:$GROUP ~/.npm
  - sudo chown -R $USER:$GROUP ~/.config
  - chmod +x ./node_modules/react-scripts/bin/react-scripts.js

install:
  - rm -rf node_modules
  - npm install
  - npm install -g yarn
  - yarn add react-scripts

script:
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
