language: node_js
node_js:
  - 12

branches:
  only:
    - main
    - dep-inclusions

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  - npm build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
