language: node_js
node_js:
  - 4

branches:
  only:
    - main
    - dep-inclusions

cache:
  directories:
    - node_modules

install:
  - nvm install node
  - npm install
  - npm install -g yarn
  - npm install react-scripts --save

script:
  - sudo yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
